apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2023-05-18 - 20:19:14 +0000
    app.quarkus.io/commit-id: 80b217a675cb1327d57400a91344d9638a2d61f6
  labels:
    app.kubernetes.io/name: quarkus-artemis
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: quarkus-artemis
spec:
  replicas: 0
  selector:
    app.kubernetes.io/name: quarkus-artemis
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  strategy:
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/build-timestamp: 2023-05-18 - 20:19:14 +0000
        app.quarkus.io/commit-id: 80b217a675cb1327d57400a91344d9638a2d61f6
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: quarkus-artemis
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.openshift.io/runtime: quarkus
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: JAVA_APP_JAR
          value: /deployments/quarkus-run.jar
        envFrom:
        - secretRef:
            name: artemis-secret
        - configMapRef:
            name: artemis-conf
        image: quay.io/rfelix/quarkus-artemis:1.0.0
        imagePullPolicy: Always
        name: quarkus-artemis
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  test: false
